use anyhow::Result;

use crate::models::{ScanReport, Severity};

pub fn to_json(report: &ScanReport) -> Result<String> {
    Ok(serde_json::to_string_pretty(report)?)
}

pub fn to_markdown(report: &ScanReport) -> String {
    let mut md = String::new();

    md.push_str("# GitHub Actions Security Report\n\n");
    md.push_str(&format!(
        "**Scanned at:** {}  \n**Workflows:** {}  \n**Findings:** {}\n\n",
        report.scanned_at.format("%Y-%m-%d %H:%M UTC"),
        report.workflow_count,
        report.finding_count,
    ));

    md.push_str("---\n\n## Summary\n\n");
    md.push_str("| Severity | Count |\n|---|---|\n");
    md.push_str(&format!("| Critical | {} |\n", report.summary.critical_count));
    md.push_str(&format!("| High | {} |\n", report.summary.high_count));
    md.push_str(&format!("| Medium | {} |\n", report.summary.medium_count));
    md.push_str(&format!("| Low | {} |\n", report.summary.low_count));
    md.push_str(&format!("| Informational | {} |\n\n", report.summary.informational_count));

    if report.findings.is_empty() {
        md.push_str("---\n\n**No findings.** All scanned workflows passed security analysis.\n\n");
    } else {
        md.push_str("---\n\n## Findings\n\n");
        for finding in &report.findings {
            let icon = severity_icon(&finding.severity);
            md.push_str(&format!(
                "### {} `{}` | {} | `{}`\n\n",
                icon, finding.severity, finding.finding_type, finding.workflow
            ));
            if let Some(job) = &finding.job_id {
                md.push_str(&format!("**Job:** `{}`  \n", job));
            }
            if let Some(step) = &finding.step_name {
                md.push_str(&format!("**Step:** `{}`  \n", step));
            }
            md.push_str(&format!("**Evidence:** `{}`  \n\n", finding.evidence));
            md.push_str(&format!("**Description:** {}  \n\n", finding.description));
            md.push_str(&format!("**Remediation:** {}  \n\n", finding.remediation));
            if let Some(cwe) = &finding.cwe {
                md.push_str(&format!("**CWE:** {}  \n\n", cwe));
            }
        }
    }

    md.push_str("---\n\n*Generated by GitHub Actions Security Sandbox Simulator. RayStudio*\n");
    md
}

pub fn to_html_stub(report: &ScanReport) -> String {
    let rows: String = report
        .findings
        .iter()
        .map(|f| {
            format!(
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>\n",
                f.severity,
                f.finding_type,
                html_escape(&f.workflow),
                f.job_id.as_deref().unwrap_or("-"),
                html_escape(&f.title),
            )
        })
        .collect();

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>GHAss Security Report</title>
<style>body{{font-family:sans-serif;max-width:1200px;margin:auto;padding:20px}}
table{{border-collapse:collapse;width:100%}}th,td{{border:1px solid #ddd;padding:8px;text-align:left}}
th{{background:#f2f2f2}}tr:hover{{background:#f5f5f5}}</style></head>
<body>
<h1>GitHub Actions Security Report</h1>
<p>Scanned: {} | Workflows: {} | Findings: {}</p>
<table>
<tr><th>Severity</th><th>Type</th><th>Workflow</th><th>Job</th><th>Title</th></tr>
{}
</table>
<p><em>Generated by GitHub Actions Security Sandbox Simulator. RayStudio</em></p>
</body></html>"#,
        report.scanned_at.format("%Y-%m-%d %H:%M UTC"),
        report.workflow_count,
        report.finding_count,
        rows,
    )
}

/// Full SARIF 2.1.0 output: populated `region.startLine` (best-effort, see
/// `ghass_scan::line_index`) and a stable `partialFingerprints` hash per
/// result so tools consuming this (e.g. GitHub code scanning) can dedupe
/// the same finding across repeated scans.
pub fn to_sarif(report: &ScanReport) -> String {
    use std::collections::HashSet;
    let mut seen_rule_ids: HashSet<String> = HashSet::new();
    let rules: Vec<serde_json::Value> = report
        .findings
        .iter()
        .filter_map(|f| {
            let id = format!("{:?}", f.finding_type);
            if seen_rule_ids.insert(id.clone()) {
                Some(serde_json::json!({
                    "id": id,
                    "shortDescription": { "text": f.title },
                    "help": { "text": f.remediation },
                }))
            } else {
                None
            }
        })
        .collect();

    let results: Vec<serde_json::Value> = report
        .findings
        .iter()
        .map(|f| {
            let mut physical_location = serde_json::json!({
                "artifactLocation": { "uri": f.workflow }
            });
            if let Some(line) = f.line {
                physical_location["region"] = serde_json::json!({
                    "startLine": line,
                });
            }

            serde_json::json!({
                "ruleId": format!("{:?}", f.finding_type),
                "level": sarif_level(&f.severity),
                "message": { "text": f.description },
                "locations": [{ "physicalLocation": physical_location }],
                "partialFingerprints": {
                    "primaryLocationLineHash/v1": fingerprint(f),
                },
            })
        })
        .collect();

    let sarif = serde_json::json!({
        "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "ghass",
                    "version": env!("CARGO_PKG_VERSION"),
                    "rules": rules,
                }
            },
            "results": results,
        }]
    });

    serde_json::to_string_pretty(&sarif).unwrap_or_default()
}

fn fingerprint(finding: &crate::models::Finding) -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let mut hasher = DefaultHasher::new();
    format!("{:?}", finding.finding_type).hash(&mut hasher);
    finding.workflow.hash(&mut hasher);
    finding.job_id.hash(&mut hasher);
    finding.step_name.hash(&mut hasher);
    finding.evidence.hash(&mut hasher);
    format!("{:016x}", hasher.finish())
}

fn severity_icon(s: &Severity) -> &'static str {
    match s {
        Severity::Critical => "🔴",
        Severity::High => "🟠",
        Severity::Medium => "🟡",
        Severity::Low => "🔵",
        Severity::Informational => "⚪",
    }
}

fn sarif_level(s: &Severity) -> &'static str {
    match s {
        Severity::Critical | Severity::High => "error",
        Severity::Medium => "warning",
        Severity::Low | Severity::Informational => "note",
    }
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{Finding, FindingSummary, FindingType};
    use chrono::{TimeZone, Utc};

    fn sample_finding() -> Finding {
        Finding {
            workflow: "wf.yml".to_string(),
            job_id: Some("build".to_string()),
            step_name: Some("run".to_string()),
            finding_type: FindingType::ScriptInjection,
            severity: Severity::Critical,
            title: "Injectable".to_string(),
            description: "desc <b>with html</b>".to_string(),
            evidence: "some evidence".to_string(),
            remediation: "fix it".to_string(),
            cwe: Some("CWE-78".to_string()),
            line: Some(42),
        }
    }

    fn report_with(findings: Vec<Finding>) -> ScanReport {
        ScanReport {
            scanned_at: Utc.with_ymd_and_hms(2026, 7, 15, 12, 0, 0).unwrap(),
            workflow_count: 1,
            finding_count: findings.len(),
            summary: FindingSummary {
                critical_count: findings
                    .iter()
                    .filter(|f| f.severity == Severity::Critical)
                    .count(),
                ..Default::default()
            },
            findings,
        }
    }

    #[test]
    fn to_json_round_trips_finding_count() {
        let report = report_with(vec![sample_finding()]);

        let json = to_json(&report).unwrap();
        let parsed: ScanReport = serde_json::from_str(&json).unwrap();

        assert_eq!(parsed.finding_count, 1);
        assert_eq!(parsed.findings[0].title, "Injectable");
    }

    #[test]
    fn to_markdown_includes_finding_details() {
        let report = report_with(vec![sample_finding()]);

        let md = to_markdown(&report);

        // NOTE: finding.title is not currently rendered anywhere in the markdown
        // output (only severity/type/workflow/job/step/evidence/description/
        // remediation/cwe are) -- this test documents actual behavior, it does
        // not assert the title is present.
        assert!(md.contains("wf.yml"));
        assert!(md.contains("some evidence"));
        assert!(md.contains("fix it"));
        assert!(md.contains("CWE-78"));
        assert!(md.contains("| Critical | 1 |"));
    }

    #[test]
    fn to_markdown_with_no_findings_says_so() {
        let report = report_with(vec![]);

        let md = to_markdown(&report);

        assert!(md.contains("No findings."));
    }

    #[test]
    fn to_html_stub_escapes_finding_title() {
        let mut finding = sample_finding();
        finding.title = "<script>alert(1)</script>".to_string();
        let report = report_with(vec![finding]);

        let html = to_html_stub(&report);

        assert!(!html.contains("<script>alert(1)</script>"));
        assert!(html.contains("&lt;script&gt;"));
    }

    #[test]
    fn to_sarif_produces_valid_json_with_expected_shape() {
        let report = report_with(vec![sample_finding()]);

        let sarif = to_sarif(&report);
        let value: serde_json::Value = serde_json::from_str(&sarif).unwrap();

        assert_eq!(value["version"], "2.1.0");
        assert_eq!(value["runs"][0]["tool"]["driver"]["version"], env!("CARGO_PKG_VERSION"));
        let results = value["runs"][0]["results"].as_array().unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0]["level"], "error");
    }

    #[test]
    fn to_sarif_populates_start_line_when_finding_has_one() {
        let report = report_with(vec![sample_finding()]);

        let sarif = to_sarif(&report);
        let value: serde_json::Value = serde_json::from_str(&sarif).unwrap();

        let region =
            &value["runs"][0]["results"][0]["locations"][0]["physicalLocation"]["region"];
        assert_eq!(region["startLine"], 42);
    }

    #[test]
    fn to_sarif_omits_region_when_finding_has_no_line() {
        let mut finding = sample_finding();
        finding.line = None;
        let report = report_with(vec![finding]);

        let sarif = to_sarif(&report);
        let value: serde_json::Value = serde_json::from_str(&sarif).unwrap();

        let physical_location = &value["runs"][0]["results"][0]["locations"][0]["physicalLocation"];
        assert!(physical_location.get("region").is_none());
    }

    #[test]
    fn to_sarif_deduplicates_rules_by_finding_type() {
        let report = report_with(vec![sample_finding(), sample_finding()]);

        let sarif = to_sarif(&report);
        let value: serde_json::Value = serde_json::from_str(&sarif).unwrap();

        let rules = value["runs"][0]["tool"]["driver"]["rules"]
            .as_array()
            .unwrap();
        assert_eq!(rules.len(), 1);
        let results = value["runs"][0]["results"].as_array().unwrap();
        assert_eq!(results.len(), 2);
    }

    #[test]
    fn fingerprint_is_stable_for_identical_findings_and_differs_for_different_evidence() {
        let a = fingerprint(&sample_finding());
        let b = fingerprint(&sample_finding());
        assert_eq!(a, b);

        let mut different = sample_finding();
        different.evidence = "something else".to_string();
        assert_ne!(a, fingerprint(&different));
    }

    #[test]
    fn sarif_level_maps_severity_correctly() {
        assert_eq!(sarif_level(&Severity::Critical), "error");
        assert_eq!(sarif_level(&Severity::High), "error");
        assert_eq!(sarif_level(&Severity::Medium), "warning");
        assert_eq!(sarif_level(&Severity::Low), "note");
        assert_eq!(sarif_level(&Severity::Informational), "note");
    }

    #[test]
    fn html_escape_handles_all_special_characters() {
        assert_eq!(
            html_escape("<a href=\"x\">&amp;</a>"),
            "&lt;a href=&quot;x&quot;&gt;&amp;amp;&lt;/a&gt;"
        );
    }
}
