use anyhow::Result;

use crate::models::{ScanReport, Severity};

pub fn to_json(report: &ScanReport) -> Result<String> {
    Ok(serde_json::to_string_pretty(report)?)
}

pub fn to_markdown(report: &ScanReport) -> String {
    let mut md = String::new();

    md.push_str("# GitHub Actions Security Report\n\n");
    md.push_str(&format!(
        "**Scanned at:** {}  \n**Workflows:** {}  \n**Findings:** {}\n\n",
        report.scanned_at.format("%Y-%m-%d %H:%M UTC"),
        report.workflow_count,
        report.finding_count,
    ));

    md.push_str("---\n\n## Summary\n\n");
    md.push_str("| Severity | Count |\n|---|---|\n");
    md.push_str(&format!("| Critical | {} |\n", report.summary.critical_count));
    md.push_str(&format!("| High | {} |\n", report.summary.high_count));
    md.push_str(&format!("| Medium | {} |\n", report.summary.medium_count));
    md.push_str(&format!("| Low | {} |\n", report.summary.low_count));
    md.push_str(&format!("| Informational | {} |\n\n", report.summary.informational_count));

    if report.findings.is_empty() {
        md.push_str("---\n\n**No findings.** All scanned workflows passed security analysis.\n\n");
    } else {
        md.push_str("---\n\n## Findings\n\n");
        for finding in &report.findings {
            let icon = severity_icon(&finding.severity);
            md.push_str(&format!(
                "### {} `{}` | {} | `{}`\n\n",
                icon, finding.severity, finding.finding_type, finding.workflow
            ));
            if let Some(job) = &finding.job_id {
                md.push_str(&format!("**Job:** `{}`  \n", job));
            }
            if let Some(step) = &finding.step_name {
                md.push_str(&format!("**Step:** `{}`  \n", step));
            }
            md.push_str(&format!("**Evidence:** `{}`  \n\n", finding.evidence));
            md.push_str(&format!("**Description:** {}  \n\n", finding.description));
            md.push_str(&format!("**Remediation:** {}  \n\n", finding.remediation));
            if let Some(cwe) = &finding.cwe {
                md.push_str(&format!("**CWE:** {}  \n\n", cwe));
            }
        }
    }

    md.push_str("---\n\n*Generated by GitHub Actions Security Sandbox Simulator. RayStudio*\n");
    md
}

pub fn to_html_stub(report: &ScanReport) -> String {
    let rows: String = report
        .findings
        .iter()
        .map(|f| {
            format!(
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>\n",
                f.severity,
                f.finding_type,
                html_escape(&f.workflow),
                f.job_id.as_deref().unwrap_or("-"),
                html_escape(&f.title),
            )
        })
        .collect();

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>GHAss Security Report</title>
<style>body{{font-family:sans-serif;max-width:1200px;margin:auto;padding:20px}}
table{{border-collapse:collapse;width:100%}}th,td{{border:1px solid #ddd;padding:8px;text-align:left}}
th{{background:#f2f2f2}}tr:hover{{background:#f5f5f5}}</style></head>
<body>
<h1>GitHub Actions Security Report</h1>
<p>Scanned: {} | Workflows: {} | Findings: {}</p>
<table>
<tr><th>Severity</th><th>Type</th><th>Workflow</th><th>Job</th><th>Title</th></tr>
{}
</table>
<p><em>Generated by GitHub Actions Security Sandbox Simulator. RayStudio</em></p>
</body></html>"#,
        report.scanned_at.format("%Y-%m-%d %H:%M UTC"),
        report.workflow_count,
        report.finding_count,
        rows,
    )
}

pub fn to_sarif_stub(report: &ScanReport) -> String {
    use std::collections::HashSet;
    let mut seen_rule_ids: HashSet<String> = HashSet::new();
    let rules: Vec<serde_json::Value> = report
        .findings
        .iter()
        .filter_map(|f| {
            let id = format!("{:?}", f.finding_type);
            if seen_rule_ids.insert(id.clone()) {
                Some(serde_json::json!({
                    "id": id,
                    "shortDescription": { "text": f.title },
                    "help": { "text": f.remediation },
                }))
            } else {
                None
            }
        })
        .collect();

    let results: Vec<serde_json::Value> = report
        .findings
        .iter()
        .map(|f| {
            serde_json::json!({
                "ruleId": format!("{:?}", f.finding_type),
                "level": sarif_level(&f.severity),
                "message": { "text": f.description },
                "locations": [{
                    "physicalLocation": {
                        "artifactLocation": { "uri": f.workflow }
                    }
                }]
            })
        })
        .collect();

    let sarif = serde_json::json!({
        "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "ghass",
                    "version": "0.1.0",
                    "rules": rules,
                }
            },
            "results": results,
        }]
    });

    serde_json::to_string_pretty(&sarif).unwrap_or_default()
}

fn severity_icon(s: &Severity) -> &'static str {
    match s {
        Severity::Critical => "🔴",
        Severity::High => "🟠",
        Severity::Medium => "🟡",
        Severity::Low => "🔵",
        Severity::Informational => "⚪",
    }
}

fn sarif_level(s: &Severity) -> &'static str {
    match s {
        Severity::Critical | Severity::High => "error",
        Severity::Medium => "warning",
        Severity::Low | Severity::Informational => "note",
    }
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
